<?php
/**
 * @file
 * @author jarrod.swift
 */
namespace ORM\Utilities;

/**
 * Test class for ConfigurationGroup.
 * Generated by PHPUnit on 2011-11-20 at 15:37:10.
 */
class ConfigurationGroupTest extends \FlexibleORMTests\ORMTest {

    /**
     * @var ConfigurationGroup $object
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        // $this->object = new ConfigurationGroup();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Covers: {className}::{origMethodName}
     * @todo Implement test__get().
     */
    public function test__get() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * Covers: {className}::{origMethodName}
     * @todo Implement testToArray().
     */
    public function testToArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
