<?php
/**
 * @file
 * @author jarrod.swift
 */
namespace ORM\Tests\Utilities;
use ORM\Utilities\ErrorHandler;
use ORM\Tests\ORMTest;

require_once dirname(__FILE__) . '/../ORMTest.php';

/**
 * Test class for ErrorHandler.
 * Generated by PHPUnit on 2011-11-15 at 20:55:31.
 */
class ErrorHandlerTest extends ORMTest {

    /**
     * @var ErrorHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testRegisterErrorHandler().
     */
    public function testRegisterErrorHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRegisterShutdownHandler().
     */
    public function testRegisterShutdownHandler() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testHandleError().
     */
    public function testHandleError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDisplayErrorOfType().
     */
    public function testDisplayErrorOfType() {
        $errorHandler = new ErrorHandler();
        
        error_reporting(E_ALL ^ E_NOTICE);
        
        $this->assertTrue( $errorHandler->displayErrorOfType(E_ERROR), "Failed to display E_ERROR");
        $this->assertTrue( $errorHandler->displayErrorOfType(E_USER_WARNING), "Failed to display E_USER_WARNING");
        $this->assertFalse( $errorHandler->displayErrorOfType(E_NOTICE), "Incorrectly displayed E_NOTICE");
        
        error_reporting(E_ALL);
        $this->assertTrue( $errorHandler->displayErrorOfType(E_NOTICE), "Failed to display E_NOTICE");
    }

}
