<?php
/**
 * @file
 * @author jarrod.swift
 */
namespace ORM\SDB;

use PHPUnit_Framework_TestCase;

/**
 * Test class for NextTokenCache.
 * Generated by PHPUnit on 2011-11-20 at 15:09:41.
 */
class NextTokenCacheTest  extends PHPUnit_Framework_TestCase {

    /**
     * @var NextTokenCache $object
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new NextTokenCache;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Covers: {className}::{origMethodName}
     * @todo Implement testStore().
     */
    public function testStore() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * Covers: {className}::{origMethodName}
     * @todo Implement testGetToken().
     */
    public function testGetToken() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * Covers: {className}::{origMethodName}
     * @todo Implement testGetNearestToken().
     */
    public function testGetNearestToken() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}