<?php

namespace ORM\Controller;

require_once '../ORMTest.php';

/**
 * Test class for ControllerFactory.
 * Generated by PHPUnit on 2011-12-02 at 12:29:56.
 */
class ControllerFactoryTest extends \ORM\Tests\ORMTest {

    /**
     * @var ControllerFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ControllerFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGet().
     */
    public function testGet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testRegisterControllers().
     */
    public function testRegisterControllers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}