<?php

namespace ORM\Controller;

/**
 * Test class for ControllerFactory.
 * Generated by PHPUnit on 2011-12-02 at 12:29:56.
 */
class ControllerFactoryTest extends \FlexibleORMTests\ORMTest {

    /**
     * @var ControllerFactory $factory
     */
    protected $factory;
    /**
     *
     * @var ControllerRegister $register
     */
    protected $register;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->register = new ControllerRegister();
        $this->register->registerNamespace('\FlexibleORMTests\Mock\Controller');
        $this->factory  = new ControllerFactory( $this->register );
    }

    public function testGet() {
        $controller = $this->factory->get( 'cars' );
        $this->assertInstanceOf('\FlexibleORMTests\Mock\Controller\Cars', $controller);
    }
    
    public function testGetWithArgs() {
        $request = new Request( array('test'=> 'array'), $_GET);
        $template = new SmartyTemplate();
        $controller = $this->factory->get( 'cars', array( $request, $template ) );
        
        $this->assertEquals( $request, $controller->getRequest() );
        $this->assertEquals( $template, $controller->getTemplate() );
    }

    /**
     * @expectedException \ORM\Exceptions\ControllerDoesNotExistException
     */
    public function testGetInvalid() {
        $this->factory->get( 'test' );
    }
    
    /**
     * @expectedException \ORM\Exceptions\ControllerDoesNotExistException
     */
    public function testGetUnknown() {
        $this->factory->get( 'unknown' );
    }
    
    public function testGetRegister() {
        $this->assertEquals( $this->register, $this->factory->getRegister() );
    }
    
    public function testSetRegister() {
        $register = new ControllerRegister();
        $register->registerNamespace('\FlexibleORMTests\Mock\AlternateController');
        $this->factory->setRegister($register);
        
        $controller = $this->factory->get( 'owners' );
        $this->assertInstanceOf('\FlexibleORMTests\Mock\AlternateController\Owners', $controller);
    }
}